// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDylF0lR1XqtRzighAbI1bfCSrX-PnUcTY',
    appId: '1:278474166629:web:33b6598ec0b2153155918c',
    messagingSenderId: '278474166629',
    projectId: 'mywallet-df2d2',
    authDomain: 'mywallet-df2d2.firebaseapp.com',
    storageBucket: 'mywallet-df2d2.firebasestorage.app',
    measurementId: 'G-XK0RE0S3W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpF8zQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    appId: '1:278474166629:android:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '278474166629',
    projectId: 'mywallet-df2d2',
    storageBucket: 'mywallet-df2d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpF8zQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    appId: '1:278474166629:ios:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '278474166629',
    projectId: 'mywallet-df2d2',
    storageBucket: 'mywallet-df2d2.appspot.com',
    iosBundleId: 'com.example.myPocketWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpF8zQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    appId: '1:278474166629:macos:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '278474166629',
    projectId: 'mywallet-df2d2',
    storageBucket: 'mywallet-df2d2.appspot.com',
    iosBundleId: 'com.example.myPocketWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpF8zQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    appId: '1:278474166629:windows:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '278474166629',
    projectId: 'mywallet-df2d2',
    authDomain: 'mywallet-df2d2.firebaseapp.com',
    storageBucket: 'mywallet-df2d2.appspot.com',
  );
}